### ISSUE TITLE
Cloud Storage validation failed shows up  in Event History

### ISSUE THREAD

**Issue by mmehra12** [cloudera/cloudera-partners#14]
Scenario:
Execute environment creation

Expected Result:
After the environment is created, the event history should not show any errors or warnings

Obtained Result:
After the environment is created, the event history shows an error around Cloud Storage Validation failed.

**Comment by mmehra12** [comment]
![Uploading Screenshot 2024-07-08 at 12.13.16 PM.png…]()

**Comment by kuldeepsahu1105** [comment]
This is expected while using the cdp-tf-quickstart i.e. Terraform based automation to deploy the CDP Infra on AWS, besides that we didn't observed any issues on the deployed environments.
